# -*- coding: utf-8 -*-
"""Recruit Restaurant Visitor Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIRzoY19iI0JVC5Kz0Fo0vj5M1ChU8rP

# Recruit Restaurant Visitor Forecasting - EDA Mini Project

**Goal:** Analyze visitor patterns (day-of-week, weekend vs weekday, monthly trends) to generate operational insights.

## Dataset
- Source: Kaggle "Recruit Restaurant Visitor Forecasting"
- File used: 'air_visit_data.csv'
- Key columns:
  - 'visit_date' : date of restaurant visit
  - 'visitors' : number of visitors
  - 'air_store_id' : restaurant identifier

## Methods
1. Loaded restaurant visitor data into a pandas DataFrame.
2. Converted the 'visit_date' column from object to datetime format.
3. Created time-based features:
   - 'day_of_week' using '.dt.day_name()'
   - 'is_weekend' using boolean logic
   - 'month' using '.dt.month'
4. Calculated average visitors using 'groupby' and 'mean'.
5. Visualized patterns using bar charts and line charts.

## Results
The following sections summarize key patterns observed in restaurant visitor traffic.

## Data Loading
The dataset was uploaded and loaded into the Colab environment for analysis.
"""

from google.colab import files
files.upload()

import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.grid'] = True

df = pd.read_csv("air_visit_data.csv")
df.head()

df.info()
df.describe()

df['visit_date'] = pd.to_datetime(df['visit_date'])

df['day_of_week'] = df['visit_date'].dt.day_name()
df[['visit_date','day_of_week','visitors']].head()

"""### Average Visitors by Day of Week

We grouped the data by day of the week and calculated the average number of visitors to understand weekly demand patterns.
"""

dow_avg = df.groupby('day_of_week')['visitors'].mean()
dow_avg

order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
dow_avg_reordered = dow_avg.reindex(order)
dow_avg_reordered

dow_avg_reordered.plot(kind='bar')
plt.xlabel('Day of Week')
plt.ylabel('Average Number of Visitors')
plt.title('Average Visitors by Day of Week')
plt.show()

"""**Interpretation:**

Average visitor counts vary across the week. Higher traffic on certain days, particularly weekends, suggests weekly patterns that could inform staffing and operational decisions.

### Weekend vs Weekday Average Visitors

We compared average visitor counts between weekends and weekdays to examine whether a weekend effect exists.
"""

df['is_weekend'] = df['day_of_week'].isin(['Saturday', 'Sunday'])

df[['day_of_week', 'is_weekend']].head(10)

weekend_avg = df.groupby('is_weekend')['visitors'].mean()
weekend_avg

weekend_avg.plot(kind='bar')
plt.xlabel('Is Weekend')
plt.ylabel('Average Number of Visitors')
plt.title('Weekend vs Weekday Average Visitors')
plt.show()

"""**Interpretation:**  
The results indicate that average visitor numbers differ between weekends and weekdays, supporting the presence of a weekend effect in restaurant demand.

### Average Visitors by Month

We calculated average visitors by month to explore potential seasonal or time-based trends.
"""

df['month'] = df['visit_date'].dt.month
df[['visit_date', 'month']].head()

month_avg = df.groupby('month')['visitors'].mean()
month_avg

import matplotlib.pyplot as plt

month_avg.plot(kind='line',marker='o')
plt.xlabel('Month')
plt.ylabel('Average Number of Visitors')
plt.title('Average Visitors by Month')
plt.show()

"""**Interpretation:**  
Monthly averages fluctuate throughout the year, which may reflect seasonality, holidays, or promotional events affecting visitor behavior.

## Key Insights
- Visitor demand shows clear weekly patterns across days of the week.
- Weekend visitor averages differ from weekdays, indicating a weekend effect.
- Monthly fluctuations suggest seasonality or event-driven changes in demand.

## Next Steps
- Analyze visitor patterns at the individual store level using `air_store_id`.
- Examine variability and outliers, not just averages.
- Incorporate holiday or event indicators to better explain demand spikes.
"""